sudo: required
dist: trusty
language: c
env:
  matrix:
    - PGVERSION=9.5 CITUS_INITIAL_VERSION=5.2 CITUS_UPGRADE_VERSION=6.0
    - PGVERSION=9.5 CITUS_INITIAL_VERSION=5.2 CITUS_UPGRADE_VERSION=6.1
    - PGVERSION=9.5 CITUS_INITIAL_VERSION=5.2 CITUS_UPGRADE_VERSION=6.2

    - PGVERSION=9.5 CITUS_INITIAL_VERSION=6.0 CITUS_UPGRADE_VERSION=6.1
    - PGVERSION=9.5 CITUS_INITIAL_VERSION=6.0 CITUS_UPGRADE_VERSION=6.2

    - PGVERSION=9.5 CITUS_INITIAL_VERSION=6.1 CITUS_UPGRADE_VERSION=6.2

    - PGVERSION=9.6 CITUS_INITIAL_VERSION=6.0 CITUS_UPGRADE_VERSION=6.1
    - PGVERSION=9.6 CITUS_INITIAL_VERSION=6.0 CITUS_UPGRADE_VERSION=6.2

    - PGVERSION=9.6 CITUS_INITIAL_VERSION=6.1 CITUS_UPGRADE_VERSION=6.2
before_install:
  - sudo make install
  - setup_apt
  - curl https://install.citusdata.com/community/deb.sh | sudo bash
  - nuke_pg
install: install_pg
script: test_citus_upgrades
